# organization name, it's used to get github repo url, also in page title
name: kissyteam

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       kissyteam
description:
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - modulex    
 - xtemplate
 - xtpl
 - query-selector
 - logger-manager
 - modulex-ua:
     repo: kissyteam/ua
 - modulex-querystring:
     repo: kissyteam/querystring
 - modulex-path:
     repo: kissyteam/path
 - modulex-json:
     repo: kissyteam/json
 - modulex-feature:
     repo: kissyteam/feature
 - modulex-util:
     repo: kissyteam/util
 - modulex-url:
     repo: kissyteam/url
 - modulex-html-parser:
     repo: kissyteam/html-parser

# list of maintainers, this won't be sorted
maintainers:
 - name:    YiMing He
   github:  yiminghe
   npm:     yiminghe
   twitter: yiminghe
   email:   yiminghe@gmail.com
   gittip:  yiminghe

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has